-- Bootstraps the migration-tracking table used by
-- scripts/apply-pending-migrations.mjs (Software_Timeline.md Section 13).
-- Backfills it with every migration filename already known-applied as of
-- Jul 23, so the automated deploy step only picks up genuinely new files
-- going forward instead of re-attempting ~65 already-applied migrations.
create table if not exists _kairos_migrations_applied (
  filename text primary key,
  applied_at timestamptz not null default now()
);

insert into _kairos_migrations_applied (filename) values
('migration_001_counselor_dashboard.sql'),
('migration_002_profile_fields.sql'),
('migration_003_stripe_idempotency.sql'),
('migration_004_rate_limits.sql'),
('migration_005_profile_expansion.sql'),
('migration_006_timeline_regen_cap.sql'),
('migration_007_college_stats_cache.sql'),
('migration_008_gpa_split.sql'),
('migration_009_premium_notify.sql'),
('migration_010_intake_expansion.sql'),
('migration_011_onboarding_split.sql'),
('migration_012_living_profile_nudge.sql'),
('migration_013_outcome_logging.sql'),
('migration_014_human_escalation.sql'),
('migration_015_shared_views.sql'),
('migration_016_rec_letters.sql'),
('migration_017_scorecard_cost_data.sql'),
('migration_018_waitlist.sql'),
('migration_019_user_safety.sql'),
('migration_020_sms_nudges.sql'),
('migration_021_mock_interview.sql'),
('migration_022_mentor_loop.sql'),
('migration_023_war_room.sql'),
('migration_024_match_enrichment_fields.sql'),
('migration_025_narrative_builder.sql'),
('migration_028_counselor_review_request_status.sql'),
('migration_029_school_matches_is_manual.sql'),
('migration_030_essay_feedback_history.sql'),
('migration_031_scholarship_tracker.sql'),
('migration_032_activity_evaluation_history.sql'),
('migration_033_profiles_display_name.sql'),
('migration_034_at_risk_dismissals.sql'),
('migration_035_aggregate_snapshots.sql'),
('migration_036_generation_jobs.sql'),
('migration_037_waitlist_referrals.sql'),
('migration_038_waitlist_nurture.sql'),
('migration_039_prompt_versioning.sql'),
('migration_039_waitlist_growth_webhook.sql'),
('migration_040_narrative_suggested_activities.sql'),
('migration_041_scholarship_deadline_nudge.sql'),
('migration_042_scholarship_checklist.sql'),
('migration_043_scholarship_logo_cache.sql'),
('migration_044_school_match_lock.sql'),
('migration_045_timeline_recurring_items.sql'),
('migration_046_interview_category_difficulty.sql'),
('migration_047_activity_hours.sql'),
('migration_048_match_confidence.sql'),
('migration_049_reengagement_nudge.sql'),
('migration_050_student_referrals.sql'),
('migration_051_timeline_checkin_streak.sql'),
('migration_052_career_path_cache.sql'),
('migration_053_ai_usage_log.sql'),
('migration_054_counselor_task_assignment.sql'),
('migration_055_counselor_narrative_essay_sharing.sql'),
('migration_056_timeline_financial_aid_tag.sql'),
('migration_058_applicant_type.sql'),
('migration_059_counselor_student_notes.sql'),
('migration_060_fk_covering_indexes.sql'),
('migration_060_shared_list_reactions.sql'),
('migration_061_public_portfolio.sql'),
('migration_062_drop_war_room.sql'),
('migration_063_merit_aid_likelihood.sql'),
('migration_064_security_hardening.sql')
on conflict (filename) do nothing;
