export const metadata = { title: "Terms of Service — Kairos" };

export default function TermsPage() {
  return (
    <div className="px-5 md:px-8 py-12 max-w-2xl mx-auto w-full prose-invert">
      <h1 className="font-serif text-3xl text-text mb-2">Terms of Service</h1>
      <p className="text-text-gray text-sm mb-8">Last updated June 28, 2026</p>

      <div className="space-y-6 text-text-gray text-sm leading-relaxed">
        <section>
          <h2 className="text-text font-medium mb-2">1. What Kairos is</h2>
          <p>
            Kairos is a free web platform that gives high school students AI-generated college
            admissions guidance: school match estimates, an application timeline, and (for
            Premium subscribers) essay feedback and career path information. Kairos is a
            planning aid, not a substitute for a licensed counselor, and does not guarantee
            admission to any school.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">2. Eligibility</h2>
          <p>
            You must be at least 14 years old to create an account. By signing up, you confirm
            you meet this age requirement.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">3. AI-generated content</h2>
          <p>
            School match percentages, timeline deadlines, career path information, and essay
            feedback are generated by an AI model based on the information in your profile and
            general, publicly available data. This content can be incomplete or wrong. Always
            verify deadlines and requirements directly with each school.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">4. Your account</h2>
          <p>
            You&apos;re responsible for the accuracy of the information you submit and for keeping
            your login credentials secure. You can delete your account and all associated data
            at any time from your profile page.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">5. Premium subscriptions</h2>
          <p>
            Premium is billed monthly or annually through Stripe. You can cancel at any time;
            your Premium access continues until the end of the current billing period.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">6. Acceptable use</h2>
          <p>
            Don&apos;t submit content that is unlawful, abusive, or that infringes someone else&apos;s
            rights. We may suspend accounts that misuse the service.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">7. Disclaimer and limitation of liability</h2>
          <p>
            Kairos is provided &quot;as is&quot; without warranties of any kind. We are not liable for
            admissions outcomes, missed deadlines, or decisions made based on Kairos&apos;s
            AI-generated guidance.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">8. Changes</h2>
          <p>
            We may update these terms as the product changes. Continued use after an update
            means you accept the revised terms.
          </p>
        </section>
        <section>
          <h2 className="text-text font-medium mb-2">9. Contact</h2>
          <p>Questions about these terms can be sent to the contact address listed on our homepage.</p>
        </section>
      </div>
    </div>
  );
}
